### ISSUE TITLE
RN4020 scripting..........?

### ISSUE THREAD

**Issue by iqbalpalemad** [LieBtrau/Aiakos#1]
Can you tell me the details of scripting on a rn4020 pictile board from microchip..

i need to know how to upload a script in rn4020
what are the necessary software   for program it

**Comment by LieBtrau** [comment]
Hi,
I suggest you take the effort to read the user guide of the RN4020.  It explains in detail how to interface with the RN4020.  It also includes some scripting examples.
You don't need software to do it.  If you use a terminal emulator, you could type all the needed commands.
If you want to interface the RN4020 with an MCU, you can have a look at the [RN4020 library](https://github.com/LieBtrau/Click_BLE2_RN4020).
