### ISSUE TITLE
HF should be UHF

### ISSUE THREAD

**Issue by samyk** [LieBtrau/Aiakos#2]
Cool project!

I noticed in the [Security](https://github.com/LieBtrau/Aiakos/wiki/Security) and [LF-section](https://github.com/LieBtrau/Aiakos/wiki/LF-section), `HF` should actually be `UHF`. I would create a pull request but I don't think Github supports pull requests for Wikis.

**Comment by LieBtrau** [comment]
Hi Samy,
I've changed the pages accordingly.
